import { Grid } from '@mui/material';
import Box from '@mui/material/Box';
import CssBaseline from '@mui/material/CssBaseline';
import Divider from '@mui/material/Divider';
import Drawer from '@mui/material/Drawer';
import Toolbar from '@mui/material/Toolbar';
import { useTheme } from '@mui/material/styles';
import * as React from 'react';
import { bubbleSort, insertionSort, mergeSort } from '../../algorithms';
import { Icon, Paragraph } from '../../components';
import { generate } from '../../utils';
import { playingSubject } from '../../utils/createObservable';
import { StepperMenu } from '../Stepper/StepperMenu';
import { Visualizer } from '../Visualizer';
import { AppBar, DrawerHeader, Main } from './Home.styles';

const drawerWidth = 240;



export const Home = () => {
  const theme = useTheme();
  const [open, setOpen] = React.useState(false);

  const handleDrawer = () => {
    setOpen(!open);
  };

  const array = generate(18)

  const [isPlaying, setIsPlaying] = React.useState(false);

  React.useEffect(() => {
    const playingSubscription = playingSubject.subscribe((value) => {
      setIsPlaying(value)
    });

    return () => {
      playingSubscription.unsubscribe();
    };
  }, [])

  return (
    <Box sx={{ display: 'flex' }}>
      <CssBaseline />
      <AppBar position="fixed" open={open}>
        <Toolbar>
          <Icon icon='menu' iconColor={{ color: 'white' }} onClick={handleDrawer} />
          <Paragraph capitalized={true} size='md' textColor={{color:'white'}} >Algorithm Visualizer</Paragraph>
        </Toolbar>
      </AppBar>
      <Drawer
        sx={{
          width: drawerWidth,
          flexShrink: 0,
          '& .MuiDrawer-paper': {
            width: drawerWidth,
            boxSizing: 'border-box',
          },
        }}
        variant="persistent"
        anchor="left"
        open={open}
      >
        <DrawerHeader>
          {theme.direction === 'ltr' ? <Icon icon='chevron_left' onClick={handleDrawer} /> : <Icon icon='chevron_right' />}
        </DrawerHeader>
        <Divider />
        <StepperMenu />
      </Drawer>
      <Main open={open}>
        <DrawerHeader />
        {/* The code below will be autogenerated later */}
        <Grid container>
          <Grid item xs={12} md={6} lg={4}>
            <Visualizer arr={array} algorithm={mergeSort} algorithmName="mergeSort" playAnimation={isPlaying} />
          </Grid>
          <Grid item xs={12} md={6} lg={4}>
            <Visualizer arr={array} algorithm={insertionSort} algorithmName="insertionSort" playAnimation={isPlaying} />
          </Grid>
          <Grid item xs={12} md={6} lg={4}>
            <Visualizer arr={array} algorithm={bubbleSort} algorithmName="bubbleSort" playAnimation={isPlaying} />
          </Grid>
        </Grid>

      </Main>
    </Box>
  );
}
